
version: '3.0'

services:
  web:
    build:
      args:
        - user=sammy
        - uid=1000
      context: .
      dockerfile: Dockerfile
    image: streamberry
    
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "5000:3306"
    environment:
      MYSQL_DATABASE: streamberry
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'






# DB_CONNECTION=mysql
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=streamberry
# DB_USERNAME=root
# DB_PASSWORD=